config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  
  resources :recipes do
    post 'like', on: :member
  end
  
  resources :chefs, except: [:new]
  get '/register', to: 'chefs#new', as: 'register'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe
  
  validates :chef, uniqueness: { scope: :recipe }
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes  
  has_many :recipe_styles
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe_style.rb
class RecipeStyle < ActiveRecord::Base
  belongs_to :style
  belongs_to :recipe
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @chefs = Chef.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 4)
  end
  
  def show
    @recipes = @chef.recipes.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end
  
  def new
    @chef = Chef.new
  end
  
  def create
    @chef = Chef.new(chef_params)
    
    if @chef.save
      flash[:success] = "Your account has been created succesfully!"
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit

  end
  
  def update
    if @chef.update(chef_params)
      flash[:success] = "Your profile was updated succesfully!"
      redirect_to chef_path(@chef)
    else
      render :edit
    end
  end
  
  
  private
  
    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end
        
    def set_chef
      @chef = Chef.find(params[:id])
    end
    
    def require_same_user
      if current_user != @chef
        flash[:danger] = "You can only edit our own profile"
        redirect_to root_path
      end
    end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_user, except: [:show]
  
  def new
    @ingredient = Ingredient.new
  end
  
  def show
    @ingredient = Ingredient.find(params[:id])
    @recipes = @ingredient.recipes.paginate(page:params[:page], per_page: 4)
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Your ingredient was created succesfully"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  private
  
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    
  end
  
  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "You are logged in"
      redirect_to recipes_path
      
    else
      flash[:danger] = "Your email address or password does not match"
      render 'new'
    end
  end
  
  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to recipes_path if logged_in?
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:index, :show, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @recipes = Recipe.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 4)
  end
  
  def show
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user
    
    if @recipe.save
      flash[:success] = "Your recipe was created succesfully!"
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was updated succesfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Your selection was succesful!"
      redirect_to :back
    else
      flash[:danger] = "You can only like/dislike a recipe once"
      redirect_to :back
    end
  end
  
  private
  
    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, :style_ids, ingredient_ids: [])
    end
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
    
    def require_same_user
      if current_user != @recipe.chef
        flash[:danger] = "You can only edit our own recipes"
        redirect_to recipes_path
      end
    end
    
  def require_user_like
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end
  end
      
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :require_user, except: [:show]
  
  def new
    @style = Style.new
  end
  
  def show
    @style = Style.find(params[:id])
    @recipes = @style.recipes.paginate(page:params[:page], per_page: 4)
  end
  
  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:success] = "Style was created succesfully"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  
  private
  
    def style_params
      params.require(:style).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, size = 80)
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end
  
  def logged_in?
    !!current_user
  end
  
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class = "row">
  <div class = "well col-md-8 col-md-offset-2">
    <%= form_for @chef do |f| %>
      <div class="form-group">
        <%= f.label :chefname %>
        <%= f.text_field :chefname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
        <%= f.submit @chef.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your account" %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<ul class="nav nav-tabs">
  <li>
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li  class="active">
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate @chefs %>

<% @chefs.each do |chef| %>
<hr />
<div class="row">
  <div class="col-md-4 center">
    <%= gravatar_for chef, size = 200 %>
  </div>
  <div class="col-md-8 pull-left">
    <h3><%= chef.email %></h3>
    <span>Created at: <%= chef.created_at.strftime("%d/%m/%Y") %></span>
  </div>
</div>

<% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: @chef.chefname %>

<div class="row">
  <div class="col-md-4 center">
    <%= gravatar_for @chef, size = 200 %>
  </div>
  <div class="col-md-8 pull-left">
    <h3><%= @chef.email %></h3>
    <span>Created at: <%= @chef.created_at.strftime("%d/%m/%Y") %></span>
  </div>
</div>
<hr />
<h1><span class="label label-default"><%= @chef.chefname %>'s recipes</span></h1>
<%= will_paginate @recipes %>
<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-offset-2"></div>
    <div class="col-md-3 center">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
    <div class="col-md-7 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small>created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp
        
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>

  </div>
  <hr />
<% end %>

app/views/ingredients/_ingredient.html.erb
<span class="quiet"><small>Ingredients: <%= link_to ingredient.name, ingredient_path(ingredient) %> </small></span>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Create a Ingredient" %>

<%= render 'shared/errors', obj: @ingredient %>

<div class = "row">
  <div class = "well col-md-6 col-md-offset-3">
    <%= form_for @ingredient do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
        <%= f.submit @ingredient.new_record? ? 'Create Ingredient' : 'Edit Ingredient', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "Recipes with: " + @ingredient.name %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @ingredient.recipes.each do |recipe| %>
  <div class="row">
    
    <div class="col-md-2">
      <%= link_to chef_path(recipe.chef) do %>
      <section class="chef_info center">
        <%= gravatar_for recipe.chef, size = 100 %>
        <h5> Chef name: <%= recipe.chef.chefname %></h5>
      </section>
      <% end %>
    </div>
    
    <div class="col-md-7 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p><%= render recipe.styles %></p>
      <p><%= render recipe.ingredients %></p>
      <p>
        <span class="quiet"><small>created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp
        
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 center">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
  </div>
  <hr />
<% end %>

<%= will_paginate @recipes %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; MyRecipes 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class = "row">
  <div class = "col-md-12 text-center">
    <% flash.each do |message_type, message| %>
    <div class = "alert alert-<%= message_type %>">
      <%= message %>
      <a class = "close" data-dismiss = "alert">&times;</a>
    </div>
    <% end %>
    
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "iNutree", root_path , class: "btn btn-lg btn-success", id:"logo" %>
    <% if logged_in? %>
      <div class="nav_item dropdown ">
        <button class="btn btn-default btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          New
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><%= link_to "Recipe", new_recipe_path %></li>
          <li><%= link_to "Style", new_style_path %></li>
          <li><%= link_to "Ingredient", new_ingredient_path %></li>
        </ul>
      </div>
      <div class="nav_item pull-right">
        <%= link_to "Log out", logout_path, class: "btn btn-default btn-danger" %> 
      </div>
      <div class="nav_item dropdown pull-right">
        <button class="btn btn-default btn-warning dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= current_user.chefname %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
          <li><%= link_to "View Profile", chef_path(current_user) %></li>
        </ul>
      </div>
    <% else %>
      <div class="nav_item pull-right">
        <%= link_to "Log in", login_path, class: "btn btn-default btn-success" %> 
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyRecipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>


<div class = "row">
  <div class = "well col-md-6 col-md-offset-3">
    <%= form_tag '/login' do %>
      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, nil, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, class: "form-control" %>
      </div>
      <%= submit_tag 'Login', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2>This is the home page for the Professional Ruby on Rails Developer Course on Udemy</h2>
  <%= link_to "Sign up now!", register_path, class:"btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left"> Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left"> Manage your recipes, create reviews, like/dislike others recipes and much more!</h2>
    <p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
  </div>
    <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left"> Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class = "row">
  <div class = "well col-md-8 col-md-offset-2">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :summary %>
        <%= f.text_field :summary, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 10, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :style %>
        <%= f.collection_select :style_ids, Style.all, :id, :name, {prompt: "Select a category"}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :ingredients %>
        <br>
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cbi| %>
          <% cbi.label(class: "checkbox-inline") {cbi.check_box(class: "checkbox") + cbi.text} %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :picture %>
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png', class: "form-control" %>
      </div>
        <%= f.submit @recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @recipes.each do |recipe| %>
  <div class="row">
    
    <div class="col-md-2">
      <%= link_to chef_path(recipe.chef) do %>
      <section class="chef_info center">
        <%= gravatar_for recipe.chef, size = 100 %>
        <h5> Chef name: <%= recipe.chef.chefname %></h5>
      </section>
      <% end %>
    </div>
    
    <div class="col-md-7 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small>created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp
        
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 center">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
  </div>
  <hr />
<% end %>

<%= will_paginate @recipes %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size = 200), chef_path(@recipe.chef) %>
    <p>
      <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
      <h3>
        <%= @recipe.summary %>
        <% if logged_in? and @recipe.chef == current_user %>
          <%= link_to "Edit this Recipe", edit_recipe_path, class: "btn btn-primary pull-right" %>
        <% end %>
        <hr />
      </h3>
      <div class="show-recipe">
        <%= image_tag(@recipe.picture.url, class: "gravatar", size: "350x250") if @recipe.picture? %>
      </div>
    <div class="well">
      <p><%= render @recipe.styles %></p>
      <p><%= render @recipe.ingredients %></p>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp
        
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to "Back", recipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<!-- OBJ SHOULD BE PASSED -->

<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<!-- TITLE SHOULD BE PASSED -->

<p>
  <h1><%= title %></h1>
  <hr />
</p>

app/views/styles/_style.html.erb
<span class="quiet"><small>Style: <%= link_to style.name, style_path(style) %> </small></span>

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: "Create a Style" %>

<%= render 'shared/errors', obj: @style %>

<div class = "row">
  <div class = "well col-md-6 col-md-offset-3">
    <%= form_for @style do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
        <%= f.submit @style.new_record? ? 'Create Style' : 'Edit Style', class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: "Recipes for #{ @style.name } food"%>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @style.recipes.each do |recipe| %>
  <div class="row">
    
    <div class="col-md-2">
      <%= link_to chef_path(recipe.chef) do %>
      <section class="chef_info center">
        <%= gravatar_for recipe.chef, size = 100 %>
        <h5> Chef name: <%= recipe.chef.chefname %></h5>
      </section>
      <% end %>
    </div>
    
    <div class="col-md-7 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p><%= render recipe.styles %></p>
      <p><%= render recipe.ingredients %></p>
      <p>
        <span class="quiet"><small>created <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small>updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %> &nbsp&nbsp
        
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 center">
      <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar") if recipe.picture? %>
    </div>
    
  </div>
  <hr />
<% end %>

<%= will_paginate @recipes %>